package tildes

import (
	"fmt"
	"log/slog"
	"sort"
	"strings"

	"github.com/lepinkainen/feed-forge/pkg/feedmeta"
	"github.com/lepinkainen/feed-forge/pkg/providerfeed"
	"github.com/lepinkainen/feed-forge/pkg/providers"
)

const defaultTopic = "tech"

var previewInfo = &providers.PreviewInfo{
	Config: feedmeta.Config{
		Title:       "Tildes ~tech",
		Link:        "https://tildes.net/~tech",
		Description: "Tildes ~tech topics generated by Feed Forge",
		Author:      "Feed Forge",
		ID:          "https://tildes.net/~tech/topics.atom",
	},
	ProviderName: "Tildes",
	TemplateName: "tildes-atom",
}

// Provider implements providers.FeedProvider for Tildes group Atom feeds.
type Provider struct {
	*providers.BaseProvider
	Topics []string // bare topic names without "~" prefix, e.g. "tech"
}

// Config is the YAML/CLI configuration for the Tildes provider.
type Config struct {
	providers.GenerateConfig `yaml:",inline"`
	Topic                    string   `yaml:"topic"`
	Topics                   []string `yaml:"topics"`
}

func factory(config any) (providers.FeedProvider, error) {
	cfg, ok := config.(*Config)
	if !ok {
		return nil, fmt.Errorf("invalid config type for tildes provider: expected *tildes.Config")
	}

	topics := normalizeTopics(cfg.Topic, cfg.Topics)
	if len(topics) == 0 {
		topics = []string{defaultTopic}
	}

	return NewTildesProvider(topics...)
}

func init() {
	providers.MustRegister("tildes", &providers.ProviderInfo{
		Name:        "tildes",
		Description: "Generate RSS feeds from Tildes group Atom feeds",
		Version:     "1.0.0",
		Factory:     factory,
		ConfigFactory: func() any {
			return &Config{Topic: defaultTopic}
		},
		Preview: previewInfo,
	})
}

// NewTildesProvider creates a stateless Tildes provider for the given topics
// (e.g. "tech"). Leading "~" prefixes are tolerated and stripped.
func NewTildesProvider(topics ...string) (providers.FeedProvider, error) {
	base, err := providers.NewBaseProvider(providers.DatabaseConfig{
		UseContentDB: false, // Tildes feed is small and re-fetched each run
	})
	if err != nil {
		slog.Error("Failed to create base provider for Tildes", "error", err)
		return nil, fmt.Errorf("initialize tildes base provider: %w", err)
	}

	normalized := normalizeTopics("", topics)
	if len(normalized) == 0 {
		normalized = []string{defaultTopic}
	}

	p := &Provider{
		BaseProvider: base,
		Topics:       normalized,
	}
	p.SetGenerateFeedFunc(providerfeed.BuildGenerator(p.FetchItems, previewInfo, p.feedConfig, p.OgDB))
	return p, nil
}

func (p *Provider) feedConfig() feedmeta.Config {
	cfg := previewInfo.Config
	if len(p.Topics) == 1 {
		group := "~" + p.Topics[0]
		cfg.Title = "Tildes " + group
		cfg.Link = "https://tildes.net/" + group
		cfg.Description = "Tildes " + group + " topics generated by Feed Forge"
		cfg.ID = buildFeedURL(p.Topics[0])
		return cfg
	}

	groups := make([]string, 0, len(p.Topics))
	for _, topic := range p.Topics {
		groups = append(groups, "~"+topic)
	}
	cfg.Title = "Tildes groups"
	cfg.Link = "https://tildes.net/"
	cfg.Description = fmt.Sprintf("Tildes %s topics generated by Feed Forge", strings.Join(groups, ", "))
	cfg.ID = "https://tildes.net/topics.atom?groups=" + strings.Join(p.Topics, ",")
	return cfg
}

// FetchItems fetches the configured Tildes Atom feed and maps each entry to
// a FeedItem with Reddit-style Link/CommentsLink semantics.
func (p *Provider) FetchItems(limit int) ([]providers.FeedItem, error) {
	items := make([]providers.FeedItem, 0)
	for _, topic := range p.Topics {
		entries, err := fetchAtomFeed(buildFeedURL(topic))
		if err != nil {
			return nil, err
		}

		group := "~" + topic
		for _, e := range entries {
			votes, comments := parseVotesAndComments(e.Content)
			items = append(items, &Item{
				entry:        e,
				group:        group,
				cleanContent: cleanContent(e.Content),
				votes:        votes,
				commentCount: comments,
			})
		}
	}

	sort.SliceStable(items, func(i, j int) bool {
		return items[i].CreatedAt().After(items[j].CreatedAt())
	})

	if limit > 0 && limit < len(items) {
		items = items[:limit]
	}

	return items, nil
}
