package tildes

import (
	"fmt"
	"log/slog"

	"github.com/lepinkainen/feed-forge/pkg/feedmeta"
	"github.com/lepinkainen/feed-forge/pkg/providerfeed"
	"github.com/lepinkainen/feed-forge/pkg/providers"
)

const defaultTopic = "tech"

var previewInfo = &providers.PreviewInfo{
	Config: feedmeta.Config{
		Title:       "Tildes ~tech",
		Link:        "https://tildes.net/~tech",
		Description: "Tildes ~tech topics generated by Feed Forge",
		Author:      "Feed Forge",
		ID:          "https://tildes.net/~tech/topics.atom",
	},
	ProviderName: "Tildes",
	TemplateName: "tildes-atom",
}

// Provider implements providers.FeedProvider for Tildes group Atom feeds.
type Provider struct {
	*providers.BaseProvider
	Topic string // bare topic name without "~" prefix, e.g. "tech"
}

// Config is the YAML/CLI configuration for the Tildes provider.
type Config struct {
	providers.GenerateConfig `yaml:",inline"`
	Topic                    string `yaml:"topic"`
}

func factory(config any) (providers.FeedProvider, error) {
	cfg, ok := config.(*Config)
	if !ok {
		return nil, fmt.Errorf("invalid config type for tildes provider: expected *tildes.Config")
	}

	topic := normalizeTopic(cfg.Topic)
	if topic == "" {
		topic = defaultTopic
	}

	return NewTildesProvider(topic)
}

func init() {
	providers.MustRegister("tildes", &providers.ProviderInfo{
		Name:        "tildes",
		Description: "Generate RSS feeds from Tildes group Atom feeds",
		Version:     "1.0.0",
		Factory:     factory,
		ConfigFactory: func() any {
			return &Config{Topic: defaultTopic}
		},
		Preview: previewInfo,
	})
}

// NewTildesProvider creates a stateless Tildes provider for the given topic
// (e.g. "tech"). A leading "~" is tolerated and stripped.
func NewTildesProvider(topic string) (providers.FeedProvider, error) {
	base, err := providers.NewBaseProvider(providers.DatabaseConfig{
		UseContentDB: false, // Tildes feed is small and re-fetched each run
	})
	if err != nil {
		slog.Error("Failed to create base provider for Tildes", "error", err)
		return nil, fmt.Errorf("initialize tildes base provider: %w", err)
	}

	p := &Provider{
		BaseProvider: base,
		Topic:        normalizeTopic(topic),
	}
	p.SetGenerateFeedFunc(providerfeed.BuildGenerator(p.FetchItems, previewInfo, nil, p.OgDB))
	return p, nil
}

// FetchItems fetches the configured Tildes Atom feed and maps each entry to
// a FeedItem with Reddit-style Link/CommentsLink semantics.
func (p *Provider) FetchItems(limit int) ([]providers.FeedItem, error) {
	entries, err := fetchAtomFeed(buildFeedURL(p.Topic))
	if err != nil {
		return nil, err
	}

	group := "~" + p.Topic

	items := make([]providers.FeedItem, 0, len(entries))
	for _, e := range entries {
		votes, comments := parseVotesAndComments(e.Content)
		items = append(items, &Item{
			entry:        e,
			group:        group,
			cleanContent: cleanContent(e.Content),
			votes:        votes,
			commentCount: comments,
		})
	}

	if limit > 0 && limit < len(items) {
		items = items[:limit]
	}

	return items, nil
}
