version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - revive
  exclusions:
    paths:
      - llm-shared

linters-settings:
  govet:
    enable:
      - shadow
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - exitAfterDefer
      - rangeValCopy
      - hugeParam
      - singleCaseSwitch
      - ifElseChain
      - paramTypeCombine
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
