# Feed-Forge Configuration Example

# Reddit provider configuration
reddit:
  feed_id: ""
  username: ""
  output_path: "reddit.xml"
  score_filter: 50
  comment_filter: 10

# Hacker News provider configuration
hackernews:
  min_points: 50
  limit: 30

# Fingerpori provider configuration
fingerpori:
  limit: 100
  output_path: "fingerpori.xml"
