package oglaf

import (
	"fmt"
	"io"
	"log/slog"
	"regexp"
	"strings"
	"time"

	"github.com/lepinkainen/feed-forge/pkg/api"
	"github.com/lepinkainen/feed-forge/pkg/database"
	"github.com/lepinkainen/feed-forge/pkg/feed"
	"github.com/lepinkainen/feed-forge/pkg/filesystem"
	"github.com/lepinkainen/feed-forge/pkg/providers"
	_ "modernc.org/sqlite" // Pure Go SQLite driver
)

// Compiled regexes for RSS parsing and comic image extraction.
var (
	rssItemRegex  = regexp.MustCompile(`(?s)<item[^>]*>(.*?)</item>`)
	rssTitleRegex = regexp.MustCompile(`<title[^>]*>(?:<!\[CDATA\[(.*?)\]\]|(.*?))</title>`)
	rssLinkRegex  = regexp.MustCompile(`<link[^>]*>(.*?)</link>`)
	rssDescRegex  = regexp.MustCompile(`<description[^>]*>(?:<!\[CDATA\[(.*?)\]\]|(.*?))</description>`)
	rssPubRegex   = regexp.MustCompile(`<pubDate[^>]*>(.*?)</pubDate>`)
	rssGUIDRegex  = regexp.MustCompile(`<guid[^>]*>(.*?)</guid>`)
	stripImgRegex = regexp.MustCompile(`<img[^>]*id="strip"[^>]*src="([^"]+)"`)
	mediaRegex    = regexp.MustCompile(`src="([^"]*//media\.oglaf\.com/comic/[^"]+)"`)
)

// RSSItem represents a single RSS feed item from Oglaf
type RSSItem struct {
	Title       string
	Link        string
	Description string
	PubDate     string
	GUID        string
	ImageURL    string
}

// Item implements the FeedItem interface
type Item struct {
	*RSSItem
	imageURL string
}

// Title returns the title of the comic
func (o *Item) Title() string {
	return o.RSSItem.Title
}

// Link returns the link to the comic page
func (o *Item) Link() string {
	return o.RSSItem.Link
}

// CommentsLink returns the link as a stable ID for Atom feeds
func (o *Item) CommentsLink() string {
	return o.RSSItem.Link
}

// Author returns the author (Oglaf)
func (o *Item) Author() string {
	return "Oglaf"
}

// Score returns 0 (no scoring system)
func (o *Item) Score() int {
	return 0
}

// CommentCount returns 0 (no comments)
func (o *Item) CommentCount() int {
	return 0
}

// CreatedAt returns the publication date
func (o *Item) CreatedAt() time.Time {
	// Parse the pubDate string
	if parsed, err := time.Parse(time.RFC1123Z, o.PubDate); err == nil {
		return parsed
	}
	return time.Now()
}

// Categories returns empty categories
func (o *Item) Categories() []string {
	return []string{"comics", "oglaf"}
}

// ImageURL returns the full comic image URL
func (o *Item) ImageURL() string {
	return o.imageURL
}

// Content returns the description
func (o *Item) Content() string {
	return o.Description
}

// Provider implements the FeedProvider interface for Oglaf comics
type Provider struct {
	*providers.BaseProvider
	FeedURL string
}

// Config holds Oglaf provider configuration for the factory.
type Config struct {
	providers.GenerateConfig `yaml:",inline"`
	FeedURL                  string `yaml:"feed-url"`
}

// factory creates an Oglaf provider from configuration.
func factory(config any) (providers.FeedProvider, error) {
	cfg, ok := config.(*Config)
	if !ok {
		return nil, fmt.Errorf("invalid config type for oglaf provider: expected *oglaf.Config")
	}

	feedURL := cfg.FeedURL
	if feedURL == "" {
		feedURL = "https://www.oglaf.com/feeds/rss/"
	}

	provider := NewOglafProvider(feedURL)
	if provider == nil {
		return nil, fmt.Errorf("failed to create oglaf provider")
	}

	return provider, nil
}

func init() {
	providers.MustRegister("oglaf", &providers.ProviderInfo{
		Name:        "oglaf",
		Description: "Generate RSS feeds from Oglaf comics",
		Version:     "1.0.0",
		Factory:     factory,
		ConfigFactory: func() any {
			return &Config{FeedURL: "https://www.oglaf.com/feeds/rss/"}
		},
		Preview: &providers.PreviewInfo{
			ProviderName: "Oglaf",
			TemplateName: "oglaf-atom",
			FeedTitle:    "Oglaf Comics",
			FeedLink:     "https://www.oglaf.com/",
			Description:  "Oglaf comics with full-size images generated by Feed Forge",
			Author:       "Feed Forge",
			FeedID:       "https://www.oglaf.com/",
		},
	})
}

func comicDescription(link, imageURL, title string) string {
	return fmt.Sprintf(
		`<div style="text-align: center; padding: 10px;">
<p><a href="%s"><img src="%s" style="max-width: 100%%; height: auto;" alt="%s" /></a></p>
<p><a href="%s">View on Oglaf</a></p>
</div>`,
		link, imageURL, title, link,
	)
}

// NewOglafProvider creates a new Oglaf provider
func NewOglafProvider(feedURL string) providers.FeedProvider {
	base, err := providers.NewBaseProvider(providers.DatabaseConfig{
		ContentDBName: "oglaf.db",
		UseContentDB:  true,
	})
	if err != nil {
		slog.Error("Failed to create base provider for Oglaf", "error", err)
		return nil
	}

	return &Provider{
		BaseProvider: base,
		FeedURL:      feedURL,
	}
}

// extractFullComicURL fetches the comic page and finds the actual comic image
func extractFullComicURL(pageURL string) (string, error) {
	// Use enhanced HTTP client with proper timeout and retry policy
	client := api.NewGenericClient()
	resp, err := client.Get(pageURL, nil)
	if err != nil {
		return "", err
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	bodyStr := string(body)

	if matches := stripImgRegex.FindStringSubmatch(bodyStr); len(matches) > 1 {
		imgURL := matches[1]
		// Ensure absolute URL
		if !strings.HasPrefix(imgURL, "http") {
			if strings.HasPrefix(imgURL, "//") {
				imgURL = "https:" + imgURL
			} else if strings.HasPrefix(imgURL, "/") {
				imgURL = "https://media.oglaf.com" + imgURL
			}
		}
		return imgURL, nil
	}

	if matches := mediaRegex.FindStringSubmatch(bodyStr); len(matches) > 1 {
		imgURL := matches[1]
		if strings.HasPrefix(imgURL, "//") {
			imgURL = "https:" + imgURL
		}
		return imgURL, nil
	}

	return "", fmt.Errorf("could not find comic image on page")
}

// fetchRSSFeedIncremental fetches RSS feed and returns only new items
func (p *Provider) fetchRSSFeedIncremental(contentDB *database.Database) ([]*RSSItem, error) {
	// 1. Fetch full RSS feed
	allItems, err := p.fetchRSSFeed()
	if err != nil {
		return nil, fmt.Errorf("failed to fetch RSS feed: %w", err)
	}

	// 2. Identify new items
	newItems, err := getNewRSSItems(contentDB, allItems)
	if err != nil {
		return nil, fmt.Errorf("failed to identify new RSS items: %w", err)
	}

	// 3. Cache new RSS items
	for _, item := range newItems {
		if err := saveRSSItem(contentDB, item); err != nil {
			slog.Warn("Failed to cache RSS item", "link", item.Link, "error", err)
		}
	}

	slog.Debug("Incremental RSS fetch completed", "totalItems", len(allItems), "newItems", len(newItems))
	return newItems, nil
}

// processComicsIncremental processes comics, only extracting images for unprocessed ones
func (p *Provider) processComicsIncremental(contentDB *database.Database) ([]providers.FeedItem, error) {
	// 1. Get unprocessed comics (limit for performance)
	unprocessed, err := getUnprocessedComics(contentDB, 50)
	if err != nil {
		return nil, fmt.Errorf("failed to get unprocessed comics: %w", err)
	}

	// 2. Extract images only for unprocessed comics
	// Track which links were just processed to avoid duplicates with cached items
	justProcessed := make(map[string]bool)
	var transformedItems []providers.FeedItem
	for _, item := range unprocessed {
		imageURL, extractErr := extractFullComicURL(item.Link)
		if extractErr != nil {
			slog.Warn("Failed to extract comic image", "link", item.Link, "error", extractErr)
			if markErr := markExtractionError(contentDB, item.Link, extractErr.Error()); markErr != nil {
				slog.Error("Failed to mark extraction error", "link", item.Link, "error", markErr)
			}
			continue
		}

		if markErr := markImageExtracted(contentDB, item.Link, imageURL); markErr != nil {
			slog.Warn("Failed to mark image as extracted", "link", item.Link, "error", markErr)
		}

		item.ImageURL = imageURL
		transformed := &Item{
			RSSItem:  item,
			imageURL: imageURL,
		}

		transformed.Description = comicDescription(item.Link, imageURL, item.Title)

		transformedItems = append(transformedItems, transformed)
		justProcessed[item.Link] = true
	}

	// 3. Include already processed cached items, skipping any just processed above
	cachedItems, err := getProcessedComics(contentDB, 50)
	if err != nil {
		slog.Warn("Failed to get processed comics", "error", err)
	} else {
		for _, item := range cachedItems {
			if justProcessed[item.Link()] {
				continue
			}
			// Always set description for cached items to ensure consistent content
			item.Description = comicDescription(item.Link(), item.imageURL, item.Title())
			transformedItems = append(transformedItems, item)
		}
	}

	slog.Debug("Incremental comic processing completed", "unprocessed", len(unprocessed), "cached", len(cachedItems), "total", len(transformedItems))
	return transformedItems, nil
}

// fetchRSSFeed fetches and parses the Oglaf RSS feed
func (p *Provider) fetchRSSFeed() ([]*RSSItem, error) {
	// Use enhanced HTTP client with proper timeout and retry policy
	client := api.NewGenericClient()
	resp, err := client.Get(p.FeedURL, nil)
	if err != nil {
		return nil, err
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	// Simple RSS parsing - look for items
	bodyStr := string(body)

	matches := rssItemRegex.FindAllStringSubmatch(bodyStr, -1)

	var items []*RSSItem

	for _, match := range matches {
		if len(match) < 2 {
			continue
		}

		itemContent := match[1]

		titleMatches := rssTitleRegex.FindStringSubmatch(itemContent)
		title := ""
		if len(titleMatches) > 1 {
			title = titleMatches[1]
			if title == "" && len(titleMatches) > 2 {
				title = titleMatches[2]
			}
		}

		linkMatches := rssLinkRegex.FindStringSubmatch(itemContent)
		link := ""
		if len(linkMatches) > 1 {
			link = linkMatches[1]
		}

		descMatches := rssDescRegex.FindStringSubmatch(itemContent)
		description := ""
		if len(descMatches) > 1 {
			description = descMatches[1]
			if description == "" && len(descMatches) > 2 {
				description = descMatches[2]
			}
		}

		pubDateMatches := rssPubRegex.FindStringSubmatch(itemContent)
		pubDate := ""
		if len(pubDateMatches) > 1 {
			pubDate = pubDateMatches[1]
		}

		guidMatches := rssGUIDRegex.FindStringSubmatch(itemContent)
		guid := ""
		if len(guidMatches) > 1 {
			guid = guidMatches[1]
		}

		if title != "" && link != "" {
			items = append(items, &RSSItem{
				Title:       title,
				Link:        link,
				Description: description,
				PubDate:     pubDate,
				GUID:        guid,
				ImageURL:    "", // Will be populated later
			})
		}
	}

	return items, nil
}

// FetchItems implements the FeedProvider interface
func (p *Provider) FetchItems(limit int) ([]providers.FeedItem, error) {
	contentDB := p.ContentDB

	// Initialize database schema
	if err := initializeSchema(contentDB); err != nil {
		return nil, err
	}

	// Clean up old data
	if err := cleanupOldData(contentDB); err != nil {
		slog.Warn("Failed to cleanup old data", "error", err)
	}

	// Incremental RSS fetch
	_, err := p.fetchRSSFeedIncremental(contentDB)
	if err != nil {
		return nil, err
	}

	// Process comics incrementally
	feedItems, err := p.processComicsIncremental(contentDB)
	if err != nil {
		return nil, err
	}

	// Apply limit if specified
	if limit > 0 && len(feedItems) > limit {
		feedItems = feedItems[:limit]
	}

	return feedItems, nil
}

// GenerateFeed implements the FeedProvider interface
func (p *Provider) GenerateFeed(outfile string, reauth bool) error {
	// reauth parameter is ignored for RSS feeds (no authentication needed)

	// Fetch items using the shared FetchItems method
	feedItems, err := p.FetchItems(0)
	if err != nil {
		return err
	}

	// Ensure output directory exists
	if err := filesystem.EnsureDirectoryExists(outfile); err != nil {
		return err
	}

	// Define feed configuration
	feedConfig := feed.Config{
		Title:       "Oglaf Comics",
		Link:        "https://www.oglaf.com/",
		Description: "Oglaf comics with full-size images generated by Feed Forge",
		Author:      "Feed Forge",
		ID:          "https://www.oglaf.com/",
	}

	// Generate Atom feed using embedded templates
	if err := feed.SaveAtomFeedToFileWithEmbeddedTemplate(feedItems, "oglaf-atom", outfile, feedConfig, p.OgDB); err != nil {
		return err
	}

	feed.LogFeedGeneration(len(feedItems), outfile)
	return nil
}
