package oglaf

import (
	"context"
	"encoding/xml"
	"errors"
	"fmt"
	"html"
	"io"
	"log/slog"
	"regexp"
	"strings"
	"time"

	"github.com/lepinkainen/feed-forge/pkg/api"
	"github.com/lepinkainen/feed-forge/pkg/database"
	"github.com/lepinkainen/feed-forge/pkg/feedmeta"
	"github.com/lepinkainen/feed-forge/pkg/httpcache"
	"github.com/lepinkainen/feed-forge/pkg/providerfeed"
	"github.com/lepinkainen/feed-forge/pkg/providers"
	_ "modernc.org/sqlite" // Pure Go SQLite driver
)

// Compiled regexes for comic image extraction from the per-comic HTML pages.
var (
	stripImgRegex = regexp.MustCompile(`<img[^>]*id="strip"[^>]*src="([^"]+)"`)
	mediaRegex    = regexp.MustCompile(`src="([^"]*//media\.oglaf\.com/comic/[^"]+)"`)
)

// rssFeed mirrors the subset of the Oglaf RSS document we care about.
type rssFeed struct {
	XMLName xml.Name   `xml:"rss"`
	Channel rssChannel `xml:"channel"`
}

type rssChannel struct {
	Items []rssItemXML `xml:"item"`
}

type rssItemXML struct {
	Title       string `xml:"title"`
	Link        string `xml:"link"`
	Description string `xml:"description"`
	PubDate     string `xml:"pubDate"`
	GUID        string `xml:"guid"`
}

var previewInfo = &providers.PreviewInfo{
	Config: feedmeta.Config{
		Title:       "Oglaf Comics",
		Link:        "https://www.oglaf.com/",
		Description: "Oglaf comics with full-size images generated by Feed Forge",
		Author:      "Feed Forge",
		ID:          "https://www.oglaf.com/",
	},
	ProviderName: "Oglaf",
	TemplateName: "oglaf-atom",
}

// RSSItem represents a single RSS feed item from Oglaf.
type RSSItem struct {
	Title       string
	Link        string
	Description string
	PublishedAt time.Time
	GUID        string
	ImageURL    string
}

// Item implements the FeedItem interface
type Item struct {
	*RSSItem
}

// Title returns the title of the comic
func (o *Item) Title() string {
	return o.RSSItem.Title
}

// Link returns the link to the comic page
func (o *Item) Link() string {
	return o.RSSItem.Link
}

// CommentsLink returns the link as a stable ID for Atom feeds
func (o *Item) CommentsLink() string {
	return o.RSSItem.Link
}

// Author returns the author (Oglaf)
func (o *Item) Author() string {
	return "Oglaf"
}

// Score returns 0 (no scoring system)
func (o *Item) Score() int {
	return 0
}

// CommentCount returns 0 (no comments)
func (o *Item) CommentCount() int {
	return 0
}

// CreatedAt returns the publication date.
func (o *Item) CreatedAt() time.Time {
	return o.PublishedAt
}

// Categories returns empty categories
func (o *Item) Categories() []string {
	return []string{"comics", "oglaf"}
}

// ImageURL returns the full comic image URL
func (o *Item) ImageURL() string {
	return o.RSSItem.ImageURL
}

// Content returns the description
func (o *Item) Content() string {
	return o.Description
}

// Provider implements the FeedProvider interface for Oglaf comics
type Provider struct {
	*providers.BaseProvider
	FeedURL string
}

// Config holds Oglaf provider configuration for the factory.
type Config struct {
	providers.GenerateConfig `yaml:",inline"`
	FeedURL                  string `yaml:"feed-url"`
}

// factory creates an Oglaf provider from configuration.
func factory(config any) (providers.FeedProvider, error) {
	cfg, ok := config.(*Config)
	if !ok {
		return nil, fmt.Errorf("invalid config type for oglaf provider: expected *oglaf.Config")
	}

	feedURL := cfg.FeedURL
	if feedURL == "" {
		feedURL = "https://www.oglaf.com/feeds/rss/"
	}

	provider, err := NewOglafProvider(feedURL)
	if err != nil {
		return nil, fmt.Errorf("create oglaf provider: %w", err)
	}

	return provider, nil
}

func init() {
	providers.MustRegister("oglaf", &providers.ProviderInfo{
		Name:        "oglaf",
		Description: "Generate RSS feeds from Oglaf comics",
		Version:     "1.0.0",
		Factory:     factory,
		ConfigFactory: func() any {
			return &Config{FeedURL: "https://www.oglaf.com/feeds/rss/"}
		},
		Preview: previewInfo,
	})
}

func comicDescription(link, imageURL, title string) string {
	escapedLink := html.EscapeString(link)
	escapedImageURL := html.EscapeString(imageURL)
	escapedTitle := html.EscapeString(title)

	return fmt.Sprintf(
		`<div style="text-align: center; padding: 10px;">
<p><a href="%s"><img src="%s" style="max-width: 100%%; height: auto;" alt="%s" /></a></p>
<p><a href="%s">View on Oglaf</a></p>
</div>`,
		escapedLink, escapedImageURL, escapedTitle, escapedLink,
	)
}

// NewOglafProvider creates a new Oglaf provider
func NewOglafProvider(feedURL string) (providers.FeedProvider, error) {
	base, err := providers.NewBaseProvider(providers.DatabaseConfig{
		ContentDBName: "oglaf.db",
		UseContentDB:  true,
	})
	if err != nil {
		slog.Error("Failed to create base provider for Oglaf", "error", err)
		return nil, fmt.Errorf("initialize oglaf base provider: %w", err)
	}

	provider := &Provider{
		BaseProvider: base,
		FeedURL:      feedURL,
	}
	provider.SetGenerateFeedFunc(providerfeed.BuildGenerator(provider.FetchItems, previewInfo, nil, provider.OgDB))

	return provider, nil
}

// extractFullComicURL fetches the comic page and finds the actual comic image
func extractFullComicURL(pageURL string) (string, error) {
	// Use enhanced HTTP client with proper timeout and retry policy
	client := api.NewGenericClient()
	resp, err := client.Get(pageURL, nil)
	if err != nil {
		return "", err
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	bodyStr := string(body)

	if matches := stripImgRegex.FindStringSubmatch(bodyStr); len(matches) > 1 {
		imgURL := matches[1]
		// Ensure absolute URL
		if !strings.HasPrefix(imgURL, "http") {
			if strings.HasPrefix(imgURL, "//") {
				imgURL = "https:" + imgURL
			} else if strings.HasPrefix(imgURL, "/") {
				imgURL = "https://media.oglaf.com" + imgURL
			}
		}
		return imgURL, nil
	}

	if matches := mediaRegex.FindStringSubmatch(bodyStr); len(matches) > 1 {
		imgURL := matches[1]
		if strings.HasPrefix(imgURL, "//") {
			imgURL = "https:" + imgURL
		}
		return imgURL, nil
	}

	return "", fmt.Errorf("could not find comic image on page")
}

// fetchRSSFeedIncremental fetches RSS feed and returns only new items
func (p *Provider) fetchRSSFeedIncremental(contentDB *database.Database) ([]*RSSItem, error) {
	// 1. Fetch full RSS feed
	allItems, err := p.fetchRSSFeed()
	if err != nil {
		return nil, fmt.Errorf("failed to fetch RSS feed: %w", err)
	}

	// 2. Identify new items
	newItems, err := getNewRSSItems(contentDB, allItems)
	if err != nil {
		return nil, fmt.Errorf("failed to identify new RSS items: %w", err)
	}

	// 3. Cache new RSS items
	for _, item := range newItems {
		if err := saveRSSItem(contentDB, item); err != nil {
			slog.Warn("Failed to cache RSS item", "link", item.Link, "error", err)
		}
	}

	slog.Debug("Incremental RSS fetch completed", "totalItems", len(allItems), "newItems", len(newItems))
	return newItems, nil
}

// feedItemLimit caps how many comics appear in the generated feed. Keeping
// this small and stable is what lets RSS readers (e.g. FreshRSS) dedupe
// correctly across runs — items only leave the window when older comics are
// bumped off by newer ones, never because an arbitrary rolling batch changed.
const feedItemLimit = 25

// processComicsIncremental backfills image URLs for any unprocessed comics,
// then returns the most recent processed comics for the feed. Unprocessed
// backfill work is intentionally not returned directly: mixing freshly
// processed items into the feed caused duplicate-entry churn in readers.
func (p *Provider) processComicsIncremental(contentDB *database.Database) ([]providers.FeedItem, int, error) {
	// 1. Backfill images for unprocessed comics (bounded per run for performance).
	unprocessed, err := getUnprocessedComics(contentDB, 50)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to get unprocessed comics: %w", err)
	}

	backfilled := 0
	for _, item := range unprocessed {
		imageURL, extractErr := extractFullComicURL(item.Link)
		if extractErr != nil {
			slog.Warn("Failed to extract comic image", "link", item.Link, "error", extractErr)
			if markErr := markExtractionError(contentDB, item.Link, extractErr.Error()); markErr != nil {
				slog.Error("Failed to mark extraction error", "link", item.Link, "error", markErr)
			}
			continue
		}

		if markErr := markImageExtracted(contentDB, item.Link, imageURL); markErr != nil {
			slog.Warn("Failed to mark image as extracted", "link", item.Link, "error", markErr)
			continue
		}
		backfilled++
	}

	// 2. Return the most recent processed comics. After the backfill above,
	// any item just processed that is recent enough will appear here.
	cachedItems, err := getProcessedComics(contentDB, feedItemLimit)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to get processed comics: %w", err)
	}

	transformedItems := make([]providers.FeedItem, 0, len(cachedItems))
	for _, item := range cachedItems {
		item.Description = comicDescription(item.Link(), item.ImageURL(), item.Title())
		transformedItems = append(transformedItems, item)
	}

	slog.Debug("Incremental comic processing completed", "attempted", len(unprocessed), "backfilled", backfilled, "feedItems", len(transformedItems))
	return transformedItems, backfilled, nil
}

func (p *Provider) httpCacheStore() *httpcache.Store {
	if p == nil || p.BaseProvider == nil {
		return nil
	}
	return p.HTTPCache
}

// fetchRSSFeed fetches and parses the Oglaf RSS feed.
func (p *Provider) fetchRSSFeed() ([]*RSSItem, error) {
	// Use enhanced HTTP client with proper timeout and retry policy
	client := api.NewGenericClient()
	body, err := httpcache.CachedGet(context.Background(), client, p.httpCacheStore(), p.FeedURL, nil)
	if err != nil {
		return nil, err
	}

	var feed rssFeed
	if err := xml.Unmarshal(body, &feed); err != nil {
		return nil, fmt.Errorf("parse oglaf rss: %w", err)
	}

	items := make([]*RSSItem, 0, len(feed.Channel.Items))
	for _, raw := range feed.Channel.Items {
		if item := convertRSSItem(raw); item != nil {
			items = append(items, item)
		}
	}

	return items, nil
}

// convertRSSItem validates a parsed RSS item and returns the canonical *RSSItem,
// or nil for items missing required fields. PubDate is the only field that can
// shape-fail (missing or unparseable); title/link emptiness drops the item silently.
func convertRSSItem(raw rssItemXML) *RSSItem {
	if raw.PubDate == "" {
		slog.Warn("Skipping RSS item with missing pubDate", "link", raw.Link)
		return nil
	}
	publishedAt, err := parsePubDate(raw.PubDate)
	if err != nil {
		slog.Warn("Skipping RSS item with unparseable pubDate", "link", raw.Link, "pubDate", raw.PubDate, "error", err)
		return nil
	}
	if raw.Title == "" || raw.Link == "" {
		return nil
	}
	return &RSSItem{
		Title:       raw.Title,
		Link:        raw.Link,
		Description: raw.Description,
		PublishedAt: publishedAt.UTC(),
		GUID:        raw.GUID,
	}
}

// FetchItems implements the FeedProvider interface
func (p *Provider) FetchItems(limit int) ([]providers.FeedItem, error) {
	contentDB := p.ContentDB

	// Initialize database schema
	if err := initializeSchema(contentDB); err != nil {
		return nil, err
	}

	// Clean up old data
	if err := cleanupOldData(contentDB); err != nil {
		slog.Warn("Failed to cleanup old data", "error", err)
	}

	// Incremental RSS fetch
	rssNotModified := false
	_, err := p.fetchRSSFeedIncremental(contentDB)
	if err != nil {
		if errors.Is(err, httpcache.ErrNotModified) {
			rssNotModified = true
		} else {
			return nil, err
		}
	}

	// Process comics incrementally
	feedItems, backfilled, err := p.processComicsIncremental(contentDB)
	if err != nil {
		return nil, err
	}
	if rssNotModified && backfilled == 0 {
		return nil, httpcache.ErrNotModified
	}

	// Apply limit if specified
	if limit > 0 && len(feedItems) > limit {
		feedItems = feedItems[:limit]
	}

	return feedItems, nil
}
