package lobsters

import (
	"fmt"
	"log/slog"
	"sort"

	"github.com/lepinkainen/feed-forge/pkg/feedmeta"
	"github.com/lepinkainen/feed-forge/pkg/providerfeed"
	"github.com/lepinkainen/feed-forge/pkg/providers"
)

var previewInfo = &providers.PreviewInfo{
	Config: feedmeta.Config{
		Title:       "Lobsters",
		Link:        "https://lobste.rs/",
		Description: "lobste.rs stories generated by Feed Forge",
		Author:      "Feed Forge",
		ID:          "https://lobste.rs/hottest.json",
	},
	ProviderName: "Lobsters",
	TemplateName: "lobsters-atom",
}

// Provider implements providers.FeedProvider for lobste.rs story listings.
type Provider struct {
	*providers.BaseProvider
	Tags     []string
	MinScore int
}

// Config is the YAML/CLI configuration for the Lobsters provider.
type Config struct {
	providers.GenerateConfig `yaml:",inline"`
	Tags                     []string `yaml:"tags"`
	MinScore                 int      `yaml:"min-score"`
}

func factory(config any) (providers.FeedProvider, error) {
	cfg, ok := config.(*Config)
	if !ok {
		return nil, fmt.Errorf("invalid config type for lobsters provider: expected *lobsters.Config")
	}

	return NewLobstersProvider(cfg.MinScore, cfg.Tags...)
}

func init() {
	providers.MustRegister("lobsters", &providers.ProviderInfo{
		Name:        "lobsters",
		Description: "Generate RSS feeds from lobste.rs",
		Version:     "1.0.0",
		Factory:     factory,
		ConfigFactory: func() any {
			return &Config{MinScore: 0}
		},
		Preview: previewInfo,
	})
}

// NewLobstersProvider creates a stateless Lobsters provider filtering on the
// given minimum score and optional tags (e.g. "go", "rust"). With no tags it
// pulls from the site-wide "hottest" listing.
func NewLobstersProvider(minScore int, tags ...string) (providers.FeedProvider, error) {
	base, err := providers.NewBaseProvider(providers.DatabaseConfig{
		UseContentDB: false, // Lobsters listings are small and re-fetched each run
	})
	if err != nil {
		slog.Error("Failed to create base provider for Lobsters", "error", err)
		return nil, fmt.Errorf("initialize lobsters base provider: %w", err)
	}

	p := &Provider{
		BaseProvider: base,
		Tags:         tags,
		MinScore:     minScore,
	}
	p.SetGenerateFeedFunc(providerfeed.BuildGenerator(p.FetchItems, previewInfo, nil, p.OgDB))
	return p, nil
}

// FetchItems fetches the configured lobste.rs listing(s), dedups stories
// seen across multiple tag listings by short_id, sorts newest-first, and
// applies the minimum score filter.
func (p *Provider) FetchItems(limit int) ([]providers.FeedItem, error) {
	seen := make(map[string]struct{})
	items := make([]providers.FeedItem, 0)

	for _, url := range listingURLs(p.Tags) {
		stories, err := fetchStories(url)
		if err != nil {
			return nil, err
		}

		for _, item := range stories {
			if _, ok := seen[item.story.ShortID]; ok {
				continue
			}
			seen[item.story.ShortID] = struct{}{}

			if item.Score() < p.MinScore {
				continue
			}
			items = append(items, item)
		}
	}

	sort.SliceStable(items, func(i, j int) bool {
		return items[i].CreatedAt().After(items[j].CreatedAt())
	})

	if limit > 0 && limit < len(items) {
		items = items[:limit]
	}

	return items, nil
}
