package lemmy

import (
	"fmt"
	"log/slog"
	"net/url"
	"os"
	"sort"
	"strings"

	"github.com/lepinkainen/feed-forge/pkg/feedmeta"
	"github.com/lepinkainen/feed-forge/pkg/providerfeed"
	"github.com/lepinkainen/feed-forge/pkg/providers"
)

const (
	// JWTEnv is the environment variable that supplies the Lemmy account JWT.
	// It takes precedence over the jwt-token configuration key, so the token
	// does not have to live in a file that could be committed.
	JWTEnv = "LEMMY_JWT"

	defaultInstance = "https://lemmy.world"
	defaultSort     = "Active"
)

var previewInfo = &providers.PreviewInfo{
	Config: feedmeta.Config{
		Title:       "Lemmy",
		Link:        defaultInstance,
		Description: "Lemmy front page generated by Feed Forge",
		Author:      "Feed Forge",
		// Never the front.xml URL: this ID is rendered into the Atom feed and
		// into the generated index.html and feeds.opml.
		ID: defaultInstance,
	},
	ProviderName: "Lemmy",
	TemplateName: "lemmy-atom",
}

// Provider implements providers.FeedProvider for a Lemmy account's front page.
type Provider struct {
	*providers.BaseProvider
	Instance          string
	Sort              string
	MinScore          int
	MinComments       int
	Limit             int
	IgnoreCommunities map[string]struct{}

	jwt string
}

// Config is the YAML/CLI configuration for the Lemmy provider.
type Config struct {
	providers.GenerateConfig `yaml:",inline"`
	Instance                 string   `yaml:"instance"`
	Sort                     string   `yaml:"sort"`
	JWTToken                 string   `yaml:"jwt-token"`
	MinScore                 int      `yaml:"min-score"`
	MinComments              int      `yaml:"min-comments"`
	IgnoreCommunities        []string `yaml:"ignore-communities"`
	Limit                    int      `yaml:"limit"`
}

func factory(config any) (providers.FeedProvider, error) {
	cfg, ok := config.(*Config)
	if !ok {
		return nil, fmt.Errorf("invalid config type for lemmy provider: expected *lemmy.Config")
	}

	return NewLemmyProvider(cfg)
}

func init() {
	providers.MustRegister("lemmy", &providers.ProviderInfo{
		Name:        "lemmy",
		Description: "Generate RSS feeds from a Lemmy account front page",
		Version:     "1.0.0",
		Factory:     factory,
		ConfigFactory: func() any {
			return &Config{Instance: defaultInstance, Sort: defaultSort}
		},
		Preview: previewInfo,
	})
}

// resolveJWT returns the Lemmy account JWT, preferring the LEMMY_JWT
// environment variable over the configuration key.
func resolveJWT(configured string) string {
	if fromEnv := strings.TrimSpace(os.Getenv(JWTEnv)); fromEnv != "" {
		return fromEnv
	}
	return strings.TrimSpace(configured)
}

// NewLemmyProvider creates a stateless provider for the authenticated Lemmy
// front page feed. The account JWT must come from LEMMY_JWT or cfg.JWTToken.
func NewLemmyProvider(cfg *Config) (providers.FeedProvider, error) {
	if cfg == nil {
		cfg = &Config{}
	}

	jwt := resolveJWT(cfg.JWTToken)
	if jwt == "" {
		// Deliberately mentions neither the token nor the request URL.
		return nil, fmt.Errorf("lemmy provider requires an account JWT: set the %s environment variable or the lemmy.jwt-token configuration key", JWTEnv)
	}

	instance := strings.TrimSuffix(strings.TrimSpace(cfg.Instance), "/")
	if instance == "" {
		instance = defaultInstance
	}
	sortOrder := strings.TrimSpace(cfg.Sort)
	if sortOrder == "" {
		sortOrder = defaultSort
	}

	base, err := providers.NewBaseProvider(providers.DatabaseConfig{
		UseContentDB: false, // The front page feed is small and re-fetched each run.
	})
	if err != nil {
		slog.Error("Failed to create base provider for Lemmy", "error", err)
		return nil, fmt.Errorf("initialize lemmy base provider: %w", err)
	}

	p := &Provider{
		BaseProvider:      base,
		Instance:          instance,
		Sort:              sortOrder,
		MinScore:          cfg.MinScore,
		MinComments:       cfg.MinComments,
		Limit:             cfg.Limit,
		IgnoreCommunities: normalizeCommunitySet(cfg.IgnoreCommunities),
		jwt:               jwt,
	}
	p.SetGenerateFeedFunc(providerfeed.BuildGenerator(p.FetchItems, previewInfo, p.feedConfig, p.OgDB))
	return p, nil
}

func (p *Provider) feedConfig() feedmeta.Config {
	cfg := previewInfo.Config
	host := p.instanceHost()
	if host == "" {
		return cfg
	}

	cfg.Title = "Lemmy " + host
	cfg.Link = p.Instance
	cfg.Description = fmt.Sprintf("Lemmy %s front page generated by Feed Forge", host)
	cfg.ID = p.Instance
	return cfg
}

// instanceHost returns the bare host of the configured instance, used for
// remote-author qualification and feed metadata.
func (p *Provider) instanceHost() string {
	parsed, err := url.Parse(p.Instance)
	if err != nil {
		return ""
	}
	return parsed.Host
}

// FetchItems fetches the authenticated front page feed, drops ignored
// communities and items below the score and comment thresholds, and sorts the
// remainder newest-first.
func (p *Provider) FetchItems(limit int) ([]providers.FeedItem, error) {
	raw, err := fetchFeed(buildFrontFeedURL(p.Instance, p.jwt, p.Sort), p.Instance, p.Sort)
	if err != nil {
		return nil, err
	}

	host := p.instanceHost()
	items := make([]providers.FeedItem, 0, len(raw))
	for _, entry := range raw {
		item := parseItem(entry, host)
		if p.skip(item) {
			continue
		}
		items = append(items, item)
	}

	sort.SliceStable(items, func(i, j int) bool {
		return items[i].CreatedAt().After(items[j].CreatedAt())
	})

	effectiveLimit := limit
	if effectiveLimit <= 0 {
		effectiveLimit = p.Limit
	}
	if effectiveLimit > 0 && effectiveLimit < len(items) {
		items = items[:effectiveLimit]
	}

	return items, nil
}

// skip reports whether an item is filtered out by the configured community
// ignore list or the score and comment thresholds.
func (p *Provider) skip(item *Item) bool {
	if len(p.IgnoreCommunities) > 0 {
		if _, ignored := p.IgnoreCommunities[normalizeCommunity(item.community)]; ignored {
			return true
		}
	}
	return item.Score() < p.MinScore || item.CommentCount() < p.MinComments
}
