package youtube

import (
	"fmt"
	"log/slog"
	"sort"

	"github.com/lepinkainen/feed-forge/pkg/feedmeta"
	"github.com/lepinkainen/feed-forge/pkg/httpcache"
	"github.com/lepinkainen/feed-forge/pkg/providerfeed"
	"github.com/lepinkainen/feed-forge/pkg/providers"
)

var previewInfo = &providers.PreviewInfo{
	Config: feedmeta.Config{
		Title:       "YouTube",
		Link:        "https://www.youtube.com/",
		Description: "YouTube channel videos generated by Feed Forge",
		Author:      "Feed Forge",
		ID:          "https://www.youtube.com/feeds/videos.xml",
	},
	ProviderName: "YouTube",
	TemplateName: "youtube-atom",
}

// Provider implements providers.FeedProvider for YouTube channel Atom feeds.
type Provider struct {
	*providers.BaseProvider
	FeedURLs      []string
	Limit         int
	IncludeShorts bool
}

// Config is the YAML/CLI configuration for the YouTube provider.
type Config struct {
	providers.GenerateConfig `yaml:",inline"`
	FeedURL                  string   `yaml:"feed-url"`
	FeedURLs                 []string `yaml:"feed-urls"`
	ChannelIDs               []string `yaml:"channel-ids"`
	Limit                    int      `yaml:"limit"`
	IncludeShorts            bool     `yaml:"include-shorts"`
}

func factory(config any) (providers.FeedProvider, error) {
	cfg, ok := config.(*Config)
	if !ok {
		return nil, fmt.Errorf("invalid config type for youtube provider: expected *youtube.Config")
	}

	feedURLs := normalizeFeedURLs(cfg.FeedURL, cfg.FeedURLs, cfg.ChannelIDs)
	if len(feedURLs) == 0 {
		return nil, fmt.Errorf("youtube provider requires at least one feed-url or channel-id")
	}

	return NewYouTubeProvider(feedURLs, cfg.Limit, cfg.IncludeShorts)
}

func init() {
	providers.MustRegister("youtube", &providers.ProviderInfo{
		Name:        "youtube",
		Description: "Generate RSS feeds from YouTube channel Atom feeds",
		Version:     "1.0.0",
		Factory:     factory,
		ConfigFactory: func() any {
			return &Config{Limit: 30}
		},
		Preview: previewInfo,
	})
}

// NewYouTubeProvider creates a stateless YouTube provider for one or more feed URLs.
func NewYouTubeProvider(feedURLs []string, limit int, includeShorts bool) (providers.FeedProvider, error) {
	base, err := providers.NewBaseProvider(providers.DatabaseConfig{
		UseContentDB: false,
	})
	if err != nil {
		slog.Error("Failed to create base provider for YouTube", "error", err)
		return nil, fmt.Errorf("initialize youtube base provider: %w", err)
	}

	p := &Provider{
		BaseProvider:  base,
		FeedURLs:      feedURLs,
		Limit:         limit,
		IncludeShorts: includeShorts,
	}
	p.SetGenerateFeedFunc(providerfeed.BuildGenerator(p.FetchItems, previewInfo, p.feedConfig, p.OgDB))
	return p, nil
}

func (p *Provider) httpCacheStore() *httpcache.Store {
	if p == nil || p.BaseProvider == nil {
		return nil
	}
	return p.HTTPCache
}

func (p *Provider) feedConfig() feedmeta.Config {
	cfg := previewInfo.Config
	if len(p.FeedURLs) == 1 && isYouTubeFeedURL(p.FeedURLs[0]) {
		cfg.ID = p.FeedURLs[0]
	}
	return cfg
}

// FetchItems fetches all configured YouTube feeds, drops Shorts by default,
// deduplicates videos across feeds, sorts newest-first, and applies the limit.
func (p *Provider) FetchItems(limit int) ([]providers.FeedItem, error) {
	items := make([]providers.FeedItem, 0)
	seen := make(map[string]struct{})

	var lastErr error
	failed := 0
	for _, feedURL := range p.FeedURLs {
		feed, err := fetchAtomFeed(p.httpCacheStore(), feedURL)
		if err != nil {
			// Only reached when there is no cached copy or it exceeded
			// maxStaleAge — a real outage worth surfacing, not a transient blip.
			slog.Error("YouTube feed unavailable, skipping", "url", feedURL, "error", err)
			lastErr = err
			failed++
			continue
		}

		for _, entry := range feed.Entries {
			if !p.IncludeShorts && entry.isShort() {
				continue
			}

			key := entry.VideoID
			if key == "" {
				key = entry.alternateHref()
			}
			if key == "" {
				continue
			}
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}

			items = append(items, &Item{entry: entry, channelTitle: feed.Title})
		}
	}

	if failed > 0 && failed == len(p.FeedURLs) {
		return nil, fmt.Errorf("all %d youtube feed(s) failed: %w", failed, lastErr)
	}

	sort.SliceStable(items, func(i, j int) bool {
		return items[i].CreatedAt().After(items[j].CreatedAt())
	})

	itemLimit := p.Limit
	if limit > 0 {
		itemLimit = limit
	}
	if itemLimit > 0 && itemLimit < len(items) {
		items = items[:itemLimit]
	}

	return items, nil
}
