name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Run build-ci task
        run: task build-ci

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: feed-forge-binary
          path: build/feed-forge